<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <OutputPath>../1.6/Assemblies/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDefaultCompileItems>true</EnableDefaultCompileItems>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies.net48" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <RimWorldPath>/home/maxim/GOG Games/RimWorld/game/RimWorldLinux_Data/Managed</RimWorldPath>
  </PropertyGroup>

  <PropertyGroup>
    <ModsPath>/home/maxim/GOG Games/RimWorld/game/Mods</ModsPath>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>$(RimWorldPath)/Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>$(RimWorldPath)/UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldPath)/UnityEngine.IMGUIModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.TextRenderingModule">
      <HintPath>$(RimWorldPath)/UnityEngine.TextRenderingModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="UnityEngine.InputLegacyModule">
      <HintPath>$(RimWorldPath)/UnityEngine.InputLegacyModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(ModsPath)/Harmony/Current/Assemblies/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RimTalk">
      <HintPath>$(ModsPath)/RimTalk/1.6/Assemblies/RimTalk.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="RPD">
      <HintPath>$(ModsPath)/RimTalk_Persona_Director/Assemblies/RPD.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
